// Demo data for courses
export const courses = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    description: "Learn HTML, CSS, JavaScript, React, Node.js and more to become a full-stack web developer",
    longDescription:
      "This comprehensive course is designed to take you from beginner to professional in web development. You'll learn front-end and back-end technologies, build real-world projects, and gain the skills needed to land your first developer job or freelance clients.",
    image: "/placeholder.svg?height=400&width=600",
    category: "Development",
    level: "Beginner to Advanced",
    rating: 4.8,
    reviews: 1245,
    instructor: "John Smith",
    instructorTitle: "Senior Web Developer & Educator",
    instructorBio:
      "John has over 10 years of experience in web development and has worked with companies like Google and Facebook. He's passionate about teaching and has helped over 50,000 students learn to code.",
    instructorImage: "/placeholder.svg?height=200&width=200",
    price: 99.99,
    discount: 79.99,
    duration: "48 hours",
    lessons: 120,
    students: 15000,
    createdAt: "2023-01-15",
    slug: "web-development-bootcamp",
    learningOutcomes: [
      "Build 16+ web development projects for your portfolio",
      "Learn HTML5, CSS3, JavaScript, React, Node.js, MongoDB, and more",
      "Create a full-stack web application from scratch",
      "Understand how to connect and work with databases",
      "Deploy your applications to production",
      "Learn professional developer best practices",
    ],
    prerequisites: [
      "Basic computer skills",
      "No prior programming experience required",
      "A computer with internet access",
    ],
    curriculum: [
      {
        title: "Introduction to Web Development",
        duration: "3 hours",
        lessons: [
          { title: "Course Overview", },
          { title: "Setting Up Your Development Environment", duration: "30 min" },
          { title: "How the Internet Works", duration: "45 min" },
          { title: "Web Development Basics", duration: "1 hour" },
          { title: "Introduction to HTML", duration: "30 min" },
        ],
      },
      {
        title: "HTML Fundamentals",
        duration: "5 hours",
        lessons: [
          { title: "HTML Document Structure", duration: "45 min" },
          { title: "Text Elements and Typography", duration: "1 hour" },
          { title: "Links and Navigation", duration: "45 min" },
          { title: "Images and Multimedia", duration: "1 hour" },
          { title: "Tables and Forms", duration: "1.5 hours" },
        ],
      },
      {
        title: "CSS Fundamentals",
        duration: "6 hours",
        lessons: [
          { title: "Introduction to CSS", duration: "45 min" },
          { title: "Selectors and Properties", duration: "1 hour" },
          { title: "Box Model and Layout", duration: "1.5 hours" },
          { title: "Flexbox and Grid", duration: "2 hours" },
          { title: "Responsive Design", duration: "1 hour" },
        ],
      },
      {
        title: "JavaScript Basics",
        duration: "8 hours",
        lessons: [
          { title: "Introduction to JavaScript", duration: "1 hour" },
          { title: "Variables and Data Types", duration: "1 hour" },
          { title: "Control Flow and Loops", duration: "1.5 hours" },
          { title: "Functions and Scope", duration: "2 hours" },
          { title: "DOM Manipulation", duration: "2.5 hours" },
        ],
      },
      {
        title: "Advanced JavaScript",
        duration: "7 hours",
        lessons: [
          { title: "ES6+ Features", duration: "1.5 hours" },
          { title: "Asynchronous JavaScript", duration: "2 hours" },
          { title: "Fetch API and AJAX", duration: "1.5 hours" },
          { title: "Error Handling", duration: "1 hour" },
          { title: "JavaScript Best Practices", duration: "1 hour" },
        ],
      },
      {
        title: "React Fundamentals",
        duration: "10 hours",
        lessons: [
          { title: "Introduction to React", duration: "1 hour" },
          { title: "Components and Props", duration: "2 hours" },
          { title: "State and Lifecycle", duration: "2 hours" },
          { title: "Handling Events", duration: "1.5 hours" },
          { title: "Forms and Controlled Components", duration: "1.5 hours" },
          { title: "React Hooks", duration: "2 hours" },
        ],
      },
      {
        title: "Node.js and Express",
        duration: "6 hours",
        lessons: [
          { title: "Introduction to Node.js", duration: "1 hour" },
          { title: "NPM and Package Management", duration: "45 min" },
          { title: "Express.js Basics", duration: "1.5 hours" },
          { title: "Routing and Middleware", duration: "1.5 hours" },
          { title: "RESTful API Development", duration: "1.5 hours" },
        ],
      },
      {
        title: "MongoDB and Mongoose",
        duration: "5 hours",
        lessons: [
          { title: "Introduction to MongoDB", duration: "1 hour" },
          { title: "CRUD Operations", duration: "1.5 hours" },
          { title: "Mongoose ODM", duration: "1.5 hours" },
          { title: "Data Validation and Relationships", duration: "1 hour" },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Machine Learning A-Z: Hands-On Python & R",
    description: "Learn to create Machine Learning Algorithms in Python and R from two Data Science experts",
    image: "/placeholder.svg?height=400&width=600",
    category: "Artificial Intelligence",
    level: "Intermediate",
    rating: 4.7,
    reviews: 985,
    instructor: "Sarah Johnson",
    price: 129.99,
    discount: 89.99,
    duration: "42 hours",
    lessons: 95,
    students: 12000,
    createdAt: "2023-02-20",
    slug: "machine-learning-python-r",
    learningOutcomes: [
      "Master Machine Learning on Python & R",
      "Make accurate predictions with regression algorithms",
      "Create powerful analysis using classification algorithms",
      "Implement clustering algorithms to segment data",
      "Learn to use neural networks and deep learning",
      "Apply ML to real-world business problems",
    ],
    prerequisites: [
      "Basic mathematics knowledge",
      "Basic programming knowledge is helpful but not required",
      "A computer with internet access",
    ],
    curriculum: [
      {
        title: "Introduction to Machine Learning",
        duration: "3 hours",
        lessons: [
          { title: "What is Machine Learning?", duration: "45 min" },
          { title: "The Machine Learning Landscape", duration: "1 hour" },
          { title: "Setting Up Your Environment", duration: "1.5 hours" },
        ],
      },
      {
        title: "Data Preprocessing",
        duration: "4 hours",
        lessons: [
          { title: "Importing Libraries and Datasets", duration: "45 min" },
          { title: "Handling Missing Data", duration: "1 hour" },
          { title: "Encoding Categorical Data", duration: "1 hour" },
          { title: "Feature Scaling", duration: "1.5 hours" },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "The Complete Digital Marketing Course",
    description: "Master Digital Marketing Strategy, Social Media Marketing, SEO, YouTube, Email, Facebook Marketing",
    image: "/placeholder.svg?height=400&width=600",
    category: "Business",
    level: "All Levels",
    rating: 4.5,
    reviews: 1876,
    instructor: "Michael Brown",
    price: 149.99,
    discount: 99.99,
    duration: "52 hours",
    lessons: 110,
    students: 18000,
    createdAt: "2023-03-10",
    slug: "complete-digital-marketing",
    learningOutcomes: [
      "Grow a business online from scratch",
      "Master SEO, social media marketing, and email marketing",
      "Create effective Facebook and Google ads",
      "Build a WordPress website with no coding required",
      "Increase website traffic and conversions",
      "Develop a comprehensive digital marketing strategy",
    ],
    prerequisites: [
      "No prior marketing knowledge required",
      "A computer with internet access",
      "Willingness to implement the strategies taught",
    ],
    curriculum: [
      {
        title: "Introduction to Digital Marketing",
        duration: "3 hours",
        lessons: [
          { title: "The Digital Marketing Landscape", duration: "45 min" },
          { title: "Creating a Digital Marketing Strategy", duration: "1 hour" },
          { title: "Understanding Your Target Audience", duration: "1.5 hours" },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "UI/UX Design Masterclass",
    description: "Create beautiful user interfaces and experiences using modern design principles",
    image: "/placeholder.svg?height=400&width=600",
    category: "Design",
    level: "Intermediate",
    rating: 4.9,
    reviews: 763,
    instructor: "Emily Chen",
    price: 89.99,
    discount: 69.99,
    duration: "38 hours",
    lessons: 85,
    students: 9000,
    createdAt: "2023-04-05",
    slug: "ui-ux-design-masterclass",
    learningOutcomes: [
      "Master the principles of UI/UX design",
      "Create wireframes and prototypes",
      "Conduct effective user research",
      "Design responsive interfaces for web and mobile",
      "Create a professional design portfolio",
      "Understand design systems and component libraries",
    ],
    prerequisites: [
      "Basic design knowledge is helpful but not required",
      "A computer with internet access",
      "Figma or Adobe XD (free versions available)",
    ],
    curriculum: [
      {
        title: "Introduction to UI/UX Design",
        duration: "4 hours",
        lessons: [
          { title: "What is UI/UX Design?", duration: "45 min" },
          { title: "The Design Process", duration: "1 hour" },
          { title: "User-Centered Design Principles", duration: "1.5 hours" },
          { title: "Design Tools Overview", duration: "1 hour" },
        ],
      },
    ],
  },
  {
    id: 5,
    title: "Blockchain Development & Cryptocurrencies",
    description: "Learn to build decentralized applications on the Ethereum blockchain",
    image: "/placeholder.svg?height=400&width=600",
    category: "Blockchain",
    level: "Advanced",
    rating: 4.6,
    reviews: 542,
    instructor: "David Wilson",
    price: 199.99,
    discount: 149.99,
    duration: "45 hours",
    lessons: 98,
    students: 6000,
    createdAt: "2023-05-15",
    slug: "blockchain-development",
    learningOutcomes: [
      "Understand blockchain technology and cryptocurrencies",
      "Build smart contracts with Solidity",
      "Create decentralized applications (DApps)",
      "Implement token standards like ERC-20 and ERC-721",
      "Understand DeFi protocols and applications",
      "Deploy and test blockchain applications",
    ],
    prerequisites: [
      "JavaScript programming experience",
      "Basic understanding of web development",
      "Familiarity with cryptography concepts is helpful",
    ],
    curriculum: [
      {
        title: "Introduction to Blockchain",
        duration: "5 hours",
        lessons: [
          { title: "What is Blockchain Technology?", duration: "1 hour" },
          { title: "Cryptocurrencies and Tokens", duration: "1.5 hours" },
          { title: "Blockchain Architecture", duration: "1.5 hours" },
          { title: "Consensus Mechanisms", duration: "1 hour" },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Data Science and Analytics Bootcamp",
    description: "Master data analysis, visualization, and machine learning techniques",
    image: "/placeholder.svg?height=400&width=600",
    category: "Data Science",
    level: "Intermediate to Advanced",
    rating: 4.7,
    reviews: 892,
    instructor: "Lisa Anderson",
    price: 129.99,
    discount: 99.99,
    duration: "50 hours",
    lessons: 105,
    students: 8500,
    createdAt: "2023-06-20",
    slug: "data-science-analytics",
    learningOutcomes: [
      "Master data analysis with Python",
      "Create compelling data visualizations",
      "Apply statistical methods to real-world problems",
      "Build predictive models using machine learning",
      "Work with big data technologies",
      "Communicate insights effectively to stakeholders",
    ],
    prerequisites: [
      "Basic programming knowledge",
      "Understanding of algebra and statistics",
      "A computer with internet access",
    ],
    curriculum: [
      {
        title: "Introduction to Data Science",
        duration: "4 hours",
        lessons: [
          { title: "What is Data Science?", duration: "45 min" },
          { title: "The Data Science Process", duration: "1 hour" },
          { title: "Setting Up Your Environment", duration: "1.5 hours" },
          { title: "Introduction to Python for Data Science", duration: "1 hour" },
        ],
      },
    ],
  },
  {
    id: 7,
    title: "Advanced JavaScript: From Fundamentals to Functional JS",
    description: "Master advanced JavaScript concepts and functional programming techniques",
    image: "/placeholder.svg?height=400&width=600",
    category: "Development",
    level: "Intermediate to Advanced",
    rating: 4.8,
    reviews: 723,
    instructor: "Robert Johnson",
    price: 89.99,
    discount: 69.99,
    duration: "35 hours",
    lessons: 78,
    students: 7200,
    createdAt: "2023-07-10",
    slug: "advanced-javascript",
    learningOutcomes: [
      "Master advanced JavaScript concepts",
      "Understand functional programming principles",
      "Implement design patterns in JavaScript",
      "Write clean, maintainable code",
      "Optimize JavaScript applications for performance",
      "Build complex applications with modern JavaScript",
    ],
    prerequisites: [
      "Basic JavaScript knowledge",
      "Understanding of HTML and CSS",
      "Familiarity with web development concepts",
    ],
    curriculum: [
      {
        title: "JavaScript Fundamentals Review",
        duration: "4 hours",
        lessons: [
          { title: "Variables, Scope, and Memory", duration: "1 hour" },
          { title: "Functions and Objects", duration: "1.5 hours" },
          { title: "Prototypes and Inheritance", duration: "1.5 hours" },
        ],
      },
    ],
  },
  {
    id: 8,
    title: "iOS App Development with Swift",
    description: "Learn to build iOS applications using Swift and Xcode",
    image: "/placeholder.svg?height=400&width=600",
    category: "Development",
    level: "Intermediate",
    rating: 4.6,
    reviews: 615,
    instructor: "Jennifer Lee",
    price: 119.99,
    discount: 89.99,
    duration: "42 hours",
    lessons: 90,
    students: 5800,
    createdAt: "2023-08-05",
    slug: "ios-development-swift",
    learningOutcomes: [
      "Build iOS applications from scratch",
      "Master Swift programming language",
      "Understand iOS app architecture",
      "Implement UI with UIKit and SwiftUI",
      "Work with Core Data for persistence",
      "Publish apps to the App Store",
    ],
    prerequisites: [
      "Basic programming knowledge",
      "Mac computer with Xcode installed",
      "No prior iOS development experience required",
    ],
    curriculum: [
      {
        title: "Introduction to iOS Development",
        duration: "3 hours",
        lessons: [
          { title: "The iOS Platform", duration: "45 min" },
          { title: "Setting Up Xcode", duration: "45 min" },
          { title: "Introduction to Swift", duration: "1.5 hours" },
        ],
      },
    ],
  },
  {
    id: 9,
    title: "Cybersecurity Fundamentals",
    description: "Learn the essentials of cybersecurity and protect against common threats",
    image: "/placeholder.svg?height=400&width=600",
    category: "IT & Software",
    level: "Beginner to Intermediate",
    rating: 4.7,
    reviews: 528,
    instructor: "Mark Thompson",
    price: 99.99,
    discount: 79.99,
    duration: "38 hours",
    lessons: 82,
    students: 6300,
    createdAt: "2023-09-15",
    slug: "cybersecurity-fundamentals",
    learningOutcomes: [
      "Understand common cybersecurity threats",
      "Implement security best practices",
      "Perform basic security assessments",
      "Protect systems against malware and attacks",
      "Understand encryption and authentication",
      "Develop a security mindset",
    ],
    prerequisites: [
      "Basic IT knowledge",
      "Understanding of computer networks",
      "No prior security experience required",
    ],
    curriculum: [
      {
        title: "Introduction to Cybersecurity",
        duration: "4 hours",
        lessons: [
          { title: "The Cybersecurity Landscape", duration: "1 hour" },
          { title: "Common Threats and Vulnerabilities", duration: "1.5 hours" },
          { title: "Security Principles", duration: "1.5 hours" },
        ],
      },
    ],
  },
  {
    id: 10,
    title: "Adobe Photoshop Masterclass",
    description: "Master Adobe Photoshop from beginner to advanced techniques",
    image: "/placeholder.svg?height=400&width=600",
    category: "Design",
    level: "All Levels",
    rating: 4.8,
    reviews: 912,
    instructor: "Alex Rodriguez",
    price: 89.99,
    discount: 69.99,
    duration: "40 hours",
    lessons: 88,
    students: 10200,
    createdAt: "2023-10-10",
    slug: "photoshop-masterclass",
    learningOutcomes: [
      "Master Photoshop's interface and tools",
      "Create and manipulate images professionally",
      "Work with layers, masks, and selections",
      "Apply color correction and retouching techniques",
      "Create digital art and compositions",
      "Optimize images for print and web",
    ],
    prerequisites: [
      "No prior Photoshop experience required",
      "Adobe Photoshop installed (trial version works)",
      "A computer with internet access",
    ],
    curriculum: [
      {
        title: "Getting Started with Photoshop",
        duration: "3 hours",
        lessons: [
          { title: "Photoshop Interface Overview", duration: "45 min" },
          { title: "Working with Files", duration: "45 min" },
          { title: "Basic Tools and Functions", duration: "1.5 hours" },
        ],
      },
    ],
  },
  {
    id: 11,
    title: "Project Management Professional (PMP) Certification",
    description: "Complete preparation for the PMP certification exam",
    image: "/placeholder.svg?height=400&width=600",
    category: "Business",
    level: "Intermediate to Advanced",
    rating: 4.9,
    reviews: 845,
    instructor: "Patricia Miller",
    price: 199.99,
    discount: 149.99,
    duration: "45 hours",
    lessons: 95,
    students: 7800,
    createdAt: "2023-11-05",
    slug: "pmp-certification",
    learningOutcomes: [
      "Master all PMP exam topics",
      "Understand project management methodologies",
      "Apply project management best practices",
      "Prepare effectively for the PMP exam",
      "Earn 35 contact hours required for the exam",
      "Develop real-world project management skills",
    ],
    prerequisites: [
      "Project management experience",
      "Bachelor's degree or high school diploma",
      "Familiarity with PMI framework is helpful",
    ],
    curriculum: [
      {
        title: "Introduction to Project Management",
        duration: "4 hours",
        lessons: [
          { title: "Project Management Framework", duration: "1 hour" },
          { title: "Project Life Cycle", duration: "1 hour" },
          { title: "Project Management Processes", duration: "2 hours" },
        ],
      },
    ],
  },
  {
    id: 12,
    title: "Complete Python Programming Bootcamp",
    description: "Learn Python programming from basics to advanced concepts",
    image: "/placeholder.svg?height=400&width=600",
    category: "Development",
    level: "All Levels",
    rating: 4.7,
    reviews: 1320,
    instructor: "Daniel Clark",
    price: 99.99,
    discount: 79.99,
    duration: "44 hours",
    lessons: 98,
    students: 14500,
    createdAt: "2023-12-10",
    slug: "python-programming-bootcamp",
    learningOutcomes: [
      "Master Python programming fundamentals",
      "Work with Python libraries and frameworks",
      "Build real-world applications and scripts",
      "Understand object-oriented programming",
      "Implement data structures and algorithms",
      "Automate tasks with Python",
    ],
    prerequisites: [
      "No prior programming experience required",
      "A computer with internet access",
      "Basic computer skills",
    ],
    curriculum: [
      {
        title: "Python Basics",
        duration: "5 hours",
        lessons: [
          { title: "Introduction to Python", duration: "1 hour" },
          { title: "Variables and Data Types", duration: "1 hour" },
          { title: "Control Flow", duration: "1.5 hours" },
          { title: "Functions", duration: "1.5 hours" },
        ],
      },
    ],
  },
]
